Maintenance update: - Include The Unlicense into each scripts - More structured arguments - Cosmetic changes (tab, space, line flow, etc.)

diff --git a/megabkp b/megabkp
--- a/megabkp
+++ b/megabkp
@@ -10,26 +10,37 @@
 # Sahri Riza Umami
 #   v0.1 - 2020/05/12 10:31:36
 #        - Initial release
-#		v0.2 - 2020/06/04 17:09:42
-#				 - Files to be backed up saved as an array then iterated by 7zip
+#   v0.2 - 2020/06/04 17:09:42
+#        - Files to be backed up saved as an array then iterated by 7zip
+#
+# LICENSE ----------------------------------------------------------------------
+#
+# This is free and unencumbered software released into the public domain.
+#
+# Anyone is free to copy, modify, publish, use, compile, sell, or
+# distribute this software, either in source code form or as a compiled
+# binary, for any purpose, commercial or non-commercial, and by any
+# means.
+#
+# In jurisdictions that recognize copyright laws, the author or authors
+# of this software dedicate any and all copyright interest in the
+# software to the public domain. We make this dedication for the benefit
+# of the public at large and to the detriment of our heirs and
+# successors. We intend this dedication to be an overt act of
+# relinquishment in perpetuity of all present and future rights to this
+# software under copyright law.
+#
+# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
+# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
+# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
+# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
+# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
+# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
+# OTHER DEALINGS IN THE SOFTWARE.
+#
+# For more information, please refer to <http://unlicense.org>
 #
 # ------------------------------------------------------------------------------
-# License:
-#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
-#                    Version 2, December 2004
-#
-# Copyright (C) 2004 Sam Hocevar <sam@hocevar.net>
-#
-# Everyone is permitted to copy and distribute verbatim or modified
-# copies of this license document, and changing it is allowed as long
-# as the name is changed.
-#
-#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
-#   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
-#
-#  0. You just DO WHAT THE FUCK YOU WANT TO.
-# ------------------------------------------------------------------------------
-
 
 # VARIABLES --------------------------------------------------------------------
 
@@ -39,13 +50,13 @@ BKPNAME="$(date "+%F")-megabkp"
 BKPDIR="$HOME/MEGAsync"
 # Files to be backed up.
 declare -a BKPFILES=( \
-	"$HOME/.gnupg" \
-	"$HOME/.ssh" \
-	"$HOME/.password-store" \
-	/mnt/DataHDD/Bizz \
-	/mnt/DataHDD/Notes \
-	'/mnt/DataHDD/Tugas SD/Administrasi Kelas/2019-2020/Semester 2/Administrasi Guru Kelas IV 2019-2020.2.ods' \
-	'/mnt/DataHDD/Tugas SD/Administrasi Kelas/2019-2020/Semester 2/raw_grades.ods' \
+  "$HOME/.gnupg" \
+  "$HOME/.ssh" \
+  "$HOME/.password-store" \
+  /mnt/DataHDD/Bizz \
+  /mnt/DataHDD/Notes \
+  '/mnt/DataHDD/Tugas SD/Administrasi Kelas/2019-2020/Semester 2/Administrasi Guru Kelas IV 2019-2020.2.ods' \
+  '/mnt/DataHDD/Tugas SD/Administrasi Kelas/2019-2020/Semester 2/raw_grades.ods' \
 )
 # Password for encrypted archive. Change accordingly.
 PASS='megasync'
@@ -57,20 +68,20 @@ mapfile -t PASSWORD < <(pass $PASS)
 
 # Checking dependencies
 checking_deps() {
-	declare -a DEPS=(7z pass)
-	for ((NUM=${#DEPS[@]},i=0; i<NUM;i++)); do
-	  if command -v "${DEPS[i]}" &>/dev/null ; then
-	    unset -v 'DEPS[i]'
-	  fi
-	done
+  declare -a DEPS=(7z pass)
+  for ((NUM=${#DEPS[@]},i=0; i<NUM;i++)); do
+    if command -v "${DEPS[i]}" &>/dev/null ; then
+      unset -v 'DEPS[i]'
+    fi
+  done
 
-	# Exit if dependencies not found.
-	if [[ "${#DEPS[@]}" -gt 0 ]]; then
-	  printf '\e[31m!! %s\n\e[m'  'Package(s) not found'
-	  printf '\e[33m:: %s\n\e[m' 'Install the proper distribution package for your system:'
-	  printf '   - %s\n' "${DEPS[@]}"
-	  exit 1
-	fi
+  # Exit if dependencies not found.
+  if [[ "${#DEPS[@]}" -gt 0 ]]; then
+    printf '\e[31m!! %s\n\e[m'  'Package(s) not found'
+    printf '\e[33m:: %s\n\e[m' 'Install the proper distribution package for your system:'
+    printf '   - %s\n' "${DEPS[@]}"
+    exit 1
+  fi
 }
 
 print_usage() {
@@ -92,5 +103,5 @@ checking_deps
 
 # Loop over array of the files to be backed up then archive it.
 for ((NUM=${#BKPFILES[@]},i=0; i<NUM;i++)); do
-	7z a -mhe=on -p"${PASSWORD}" -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on "$BKPDIR/$BKPNAME.7z" "${BKPFILES[i]}"
+  7z a -mhe=on -p"${PASSWORD}" -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on "$BKPDIR/$BKPNAME.7z" "${BKPFILES[i]}"
 done
