Update xbmount

diff --git a/xbmount b/xbmount
--- a/xbmount
+++ b/xbmount
@@ -15,6 +15,8 @@
 # v0.1  - 2021/01/28 21:30:03
 #         Initial realase.
 # v0.2  - 2023/07/02 18:27:58
+# v0.3  - 2023/07/16 09:42:14
+#         - Remove mount detection
 #
 # LICENSE ----------------------------------------------------------------------
 #
@@ -47,20 +49,15 @@
 
 # VARIABLES --------------------------------------------------------------------
 
-MOUNTED=false
 # Mount directory.
 # $HOME is preferred because mounted xiso would be shown in GUI file manager.
+# DO NOT use non empty directoriy to avoid losing data when script clearing this
+# mountpoint.
 MNTDIR="$HOME/XBMount"
 # PATH to xbfuse binary.
 XBFUSE="$HOME/.local/bin/xbfuse"
 
 # FUNCTIONS --------------------------------------------------------------------
-
-is_mounted() {
-  if grep -qe "${1// /\\\\040}" /etc/mtab; then
-    MOUNTED=true
-  fi
-}
 
 print() {
   printf ':: %s\n' "$@"
@@ -95,15 +92,12 @@ Example:
 
 # MAIN -------------------------------------------------------------------------
 
+# Exit if user doesn't have sufficient permission on mountpoint.
+mkdir -p "$MNTDIR" || exit
+
 # Clean up unused mountpoint.
-while read -r mountdir; do
-  is_mounted "$mountdir"
-  if $MOUNTED; then
-    true
-  else
-    rmdir "$mountdir"
-  fi
-done < <(find "$MNTDIR" -mindepth 1 -maxdepth 1 -type d)
+# No need to check mopuntpoint as rmdir will fail on non empty directories.
+rmdir "$MNTDIR"/* 2>/dev/null
 
 if [[ $# -eq 0 ]]; then
   print_w 'No files specified.'
@@ -144,34 +138,22 @@ Extensions=iso;" > "$HOME/.local/share/nemo/actions/xisomount.nemo_action"
       exit
     fi
 
-    # Exit if user doesn't have sufficient permission on mountpoint.
-    mkdir -p "$MNTDIR" || exit
-
     # Get basename.
     XISO="${1##*/}"
     XISO="$MNTDIR/${XISO%.*}"
 
-    # If the mountpoint is in mtab, then probably the file is already mounted
-    # or the mountpoint is in use to mount another file. Better to avoid it.
-    is_mounted "$XISO"
-    if $MOUNTED; then
-      print_w 'Aborted.' "$XISO is not empty."
-      exit
-    fi
-
     mkdir -p "$XISO"
-    "$XBFUSE" "$1" "$XISO"
+    # Also check $XBFUSE error code to check if mount is succesful
+    if ! "$XBFUSE" "$1" "$XISO"; then
+      print_w "Unable to mount ${1}."
+    else
+      print_g "$1" 'has been successfully mounted on:' "$XISO"
+    fi
     # user_allow_other - Using the allow_other mount option works fine as root,
     # in order to have it work as user you need user_allow_other in
     # /etc/fuse.conf as well. (This option allows users to use the allow_other
     # option.) You need allow_other if you want users other than the owner to
     # access a mounted fuse.
     #"$XBFUSE" "$1" "$XISO" -o allow_other,default_permissions
-    is_mounted "$XISO"
-    if $MOUNTED; then
-      print_g "$1" 'has been successfully mounted on:' "$XISO"
-    else
-      print_w "Unable to mount ${1}."
-    fi
   ;;
 esac
